root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]

# OSの通知に頼らず、直接ファイルを定期チェックするモード
poll = true
# チェックする間隔（ミリ秒）
poll_interval = 500
