root = "."
tmp_dir = "tmp"

[build]
  # 変更があったら実行されるビルドコマンド
  cmd = "go build -o ./tmp/main ."
  # ビルド後に起動するバイナリ
  bin = "./tmp/main"
  # 監視するファイルの拡張子
  include_ext = ["go", "tpl", "tmpl", "html"]
  # 監視から除外するディレクトリ
  exclude_dir = ["assets", "tmp", "vendor"]
